# Generated by Django 4.2 on 2023-06-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohsori", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basket",
            old_name="use_yn",
            new_name="basket_yn",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="use_yn",
            new_name="user_yn",
        ),
        migrations.AddField(
            model_name="good",
            name="good_yn",
            field=models.CharField(help_text="사용여부", max_length=2, null=True),
        ),
    ]
