# Generated by Django 4.2 on 2023-06-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohsori", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qna",
            name="qna_img",
        ),
        migrations.AddField(
            model_name="qna",
            name="img_url",
            field=models.ImageField(
                blank=True, help_text="이미지 파일", null=True, upload_to=""
            ),
        ),
        migrations.AddField(
            model_name="qna",
            name="subject",
            field=models.CharField(default="question", help_text="질문제목", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="qna",
            name="question",
            field=models.CharField(help_text="질문"),
        ),
        migrations.AlterField(
            model_name="qna",
            name="type",
            field=models.CharField(blank=True, help_text="질문유형", null=True),
        ),
    ]
