# Generated by Django 4.2 on 2023-06-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsori', '0002_customtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_json',
            field=models.JSONField(default=dict),
        ),
    ]
