# Generated by Django 4.2 on 2023-06-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohsori", "0002_remove_faq_reg_date_goods_goods_point_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="goods_point",
            field=models.FloatField(help_text="상품별점", null=True),
        ),
        migrations.AlterField(
            model_name="goods",
            name="goods_price",
            field=models.IntegerField(help_text="상품가격", null=True),
        ),
        migrations.AlterField(
            model_name="goods",
            name="use_yn",
            field=models.CharField(help_text="사용여부", max_length=2, null=True),
        ),
    ]
