# Generated by Django 4.2 on 2023-06-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohsori", "0002_rename_use_yn_basket_basket_yn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="reg_date",
            field=models.DateTimeField(auto_now_add=True, help_text="등록일자"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="reg_date",
            field=models.DateTimeField(auto_now_add=True, help_text="등록일자"),
        ),
        migrations.AlterField(
            model_name="good",
            name="reg_date",
            field=models.DateTimeField(auto_now_add=True, help_text="등록일자"),
        ),
        migrations.AlterField(
            model_name="qna",
            name="reg_date",
            field=models.DateTimeField(auto_now_add=True, help_text="등록일자"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="reg_date",
            field=models.DateTimeField(auto_now_add=True, help_text="등록일자"),
        ),
    ]
