# Generated by Django 4.2 on 2023-06-30 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ohsori", "0002_remove_qna_qna_img_qna_img_url_qna_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qna",
            name="subject",
            field=models.CharField(
                blank=True, help_text="질문제목", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="qna",
            name="username",
            field=models.ForeignKey(
                db_column="username",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qna",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
