# Generated by Django 4.2 on 2023-07-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ohsori", "0003_alter_qna_subject_alter_qna_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Faq",
        ),
        migrations.AlterField(
            model_name="baskets",
            name="goods_no",
            field=models.ForeignKey(
                db_column="goods_no",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="ohsori.goods",
            ),
        ),
        migrations.DeleteModel(
            name="Survey",
        ),
    ]
