# Generated by Django 4.2 on 2023-06-22 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ohsori", "0003_alter_basket_reg_date_alter_faq_reg_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
