# Generated by Django 4.2 on 2023-06-22 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ohsori", "0004_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
