# Generated by Django 4.2 on 2023-07-02 17:06

from django.db import migrations, models
import ohsori.models


class Migration(migrations.Migration):

    dependencies = [
        ("ohsori", "0004_delete_faq_alter_baskets_goods_no_delete_survey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qna",
            name="img_url",
        ),
        migrations.AddField(
            model_name="qna",
            name="img_file",
            field=models.FileField(
                blank=True,
                help_text="이미지 파일",
                null=True,
                upload_to=ohsori.models.user_directory_path,
            ),
        ),
    ]
